name: publish

on:
  push:
    tags:
      - v*.*.*

env:
  PYTHON_VERSION: '3.8.9'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - run: mkdir file-icons
    - run: mkdir product-icons
    - run: python3 -m translate
    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: |
          file-icons/
          product-icons/
          thumbnails/
          *.md
          package.json

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: build
        path: .
    - run: echo VERSION=${GITHUB_REF#refs/tags/v} >> $GITHUB_ENV
    - run: npx vsce publish ${{ env.VERSION }} -p ${{ secrets.VSCE_PAT }} --no-git-tag-version
